name: Build client_cli binaries

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            binary_suffix: ubuntu_noble
            target: x86_64-unknown-linux-gnu
          - os: macos-14
            binary_suffix: macos_sonoma
            target: x86_64-apple-darwin
          - os: macos-14
            binary_suffix: macos_sonoma_arm64
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller poetry

      - name: Install project dependencies with Poetry
        run: |
          poetry install

      - name: Show direcory structure
        run: ls -R

      - name: Build client_cli
        run: |
           pyinstaller --onefile -n client_cli \ 
           -p $(poetry env info --path)/lib/python3.*/site-packages \
           mpc_demo_infra/client_cli/binary/client_cli.py

      - name: Show direcory structure
        run: ls -R

      - name: Archive binary
        run: |
          mkdir -p artifacts
          cp dist/client_cli artifacts/client_cli_${{ matrix.binary_suffix }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: client_cli_${{ matrix.binary_suffix }}
          path: artifacts/
          compression-level: 9

