name: Build share_data binaries

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            binary_suffix: ubuntu_noble
            target: x86_64-unknown-linux-gnu
          - os: macos-13
            binary_suffix: macos_ventura
            target: x86_64-apple-darwin
          - os: macos-14
            binary_suffix: macos_sonoma_arm64
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller poetry
          python -m pip install pip-system-certs --use-feature=truststore

      - name: Install project dependencies with Poetry
        run: |
          poetry install

      - name: Build share_data
        run: |
           pyinstaller --onefile -n share_data -p $(poetry env info --path)/lib/python3.*/site-packages -p $(pwd) ./mpc_demo_infra/client_cli/binary/share-data.py

      - name: Archive binary
        run: |
          mkdir -p artifacts
          cp dist/share_data artifacts/share_data_${{ matrix.binary_suffix }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: share_data_${{ matrix.binary_suffix }}
          path: artifacts/
          compression-level: 0

